#!/bin/bash
make -f binom.mak
make -f captcha.mak
make -f eeglchi.mak
make -f eegldots.mak
make -f eeglencr.mak
make -f eeglgen.mak
make -f eeglnorm.mak
make -f eeglpat.mak
make -f eeglraw.mak
make -f eegltim.mak
make -f genalfa.mak
make -f gendna.mak
make -f mcbell.mak
make -f mccos.mak
make -f mcparab.mak
make -f mcpi.mak
make -f mcsin.mak
make -f mcsph.mak
make -f pair.mak
make -f poischi.mak
make -f pwrball.mak
make -f qmatch.mak
make -f ranwlk.mak
make -f tsteegl.mak
make -f uintchi.mak
